### ISSUE TITLE
feed_dict problem 

### ISSUE THREAD

**Issue by RoeeXu** [Ubiqus/tf_rnnlm#3]
In rnnlm_ops.py, line73 to line75:
`for i, (c, h) in enumerate(model.initial_state):`
    `feed_dict[c] = state[i].c`
    `feed_dict[h] = state[i].h`
What is that meaning?
Is that mean:
LSTM's first hidden state can be copied from the previous iteration's final state.

Further more, I deleted the three lines, and the result of the small model was turned into 138.7.
How to explain it? Thank you for answering my doubts. The code is beautiful.

**Comment by pltrdy** [comment]
Hi,

That's what it means. In training case, the initial state may be passed as a parameter or loaded from checkpoint, otherwise it's a zero state.

If you are using `num_steps` your iterations may cut sentences. Therefore, it make sense to provide an iteration the LSTM state in order to provide some context. I guess this phenomenom isn't really important in the dynamic case (ie. `num_steps = 0`).

Hope it helps.

**Comment by RoeeXu** [comment]
Thank you very much!
